import { Octokit } from "octokit";
import { DriftEvent, CallSite, Fix } from "@driftlock/core";

export interface PRResult {
    url: string;
    number: number;
    branch: string;
}

export interface PRMetadata {
    driftEvent: DriftEvent;
    callSite: CallSite;
    fix: Fix;
    files: Array<{ path: string; changes: string }>;
}

export class PRGenerator {
    private octokit: Octokit;

    constructor(githubToken: string, octokit?: Octokit) {
        this.octokit = octokit ?? new Octokit({ auth: githubToken });
    }

    async createFixPR(
        owner: string,
        repo: string,
        metadata: PRMetadata,
        baseBranch: string = "main"
    ): Promise<PRResult> {
        const branchName = `driftlock/fix-${metadata.callSite.id.slice(0, 8)}`;

        const title = this.generateTitle(metadata);
        const body = this.generateBody(metadata);

        // Create branch
        const { data: baseRef } = await this.octokit.rest.git.getRef({
            owner,
            repo,
            ref: `heads/${baseBranch}`,
        });

        await this.octokit.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${branchName}`,
            sha: baseRef.object.sha,
        });

        // Apply file changes
        for (const file of metadata.files) {
            await this.updateFile(
                owner,
                repo,
                branchName,
                file.path,
                file.changes
            );
        }

        // Create PR
        const { data: pr } = await this.octokit.rest.pulls.create({
            owner,
            repo,
            title,
            body,
            head: branchName,
            base: baseBranch,
        });

        return {
            url: pr.html_url,
            number: pr.number,
            branch: branchName,
        };
    }

    private generateTitle(metadata: PRMetadata): string {
        const { fix, callSite } = metadata;
        const action =
            fix.type === "field_rename"
                ? "Rename"
                : fix.type === "type_coercion"
                  ? "Update type for"
                  : "Fix";
        return `driftlock: ${action} ${callSite.method} in ${callSite.filePath}`;
    }

    private generateBody(metadata: PRMetadata): string {
        const { driftEvent, callSite, fix } = metadata;
        const confidenceEmoji =
            driftEvent.confidence === "high"
                ? "🟢"
                : driftEvent.confidence === "medium"
                  ? "🟡"
                  : "🔴";

        return `## DriftLock Fix

### What changed
${fix.description}

### Affected call site
- **File:** \`${callSite.filePath}:${callSite.line}\`
- **Method:** \`${callSite.method}\`
- **Endpoint:** \`${callSite.endpoint ?? "pending-capture"}\`
- **HTTP Method:** ${callSite.httpMethod ?? "unknown"}

### Confidence
${confidenceEmoji} ${driftEvent.confidence.toUpperCase()}

### Diff
\`\`\`diff
${fix.diff}
\`\`\`

### Files changed
${metadata.files.map((f) => `- \`${f.path}\``).join("\n")}

---
*Generated by [DriftLock](https://github.com/nerdev-co/DriftLock). Self-maintaining APIs.*`;
    }

    private async updateFile(
        owner: string,
        repo: string,
        branch: string,
        path: string,
        content: string
    ): Promise<void> {
        // Try to get existing file
        let sha: string | undefined;
        try {
            const { data } = await this.octokit.rest.repos.getContent({
                owner,
                repo,
                path,
                ref: branch,
            });
            if ("sha" in data) {
                sha = data.sha;
            }
        } catch {
            // File doesn't exist yet
        }

        const params: any = {
            owner,
            repo,
            path,
            message: `driftlock: update ${path}`,
            content: Buffer.from(content).toString("base64"),
            branch,
        };

        if (sha) {
            params.sha = sha;
        }

        await this.octokit.rest.repos.createOrUpdateFileContents(params);
    }

    async addPRComment(
        owner: string,
        repo: string,
        prNumber: number,
        body: string
    ): Promise<void> {
        await this.octokit.rest.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body,
        });
    }
}
